server:
  session-timeout : 3600
  port: 3000

#数据库连接配置
spring:
  datasource:
    smsDB:
      url: jdbc:oracle:thin:@172.20.0.56:1521:oracle11
      username: smsdb
      password: zcl941217
      driver-class-name: oracle.jdbc.OracleDriver
    efdDB:
      url: jdbc:oracle:thin:@172.20.0.228:1521:oracle11
      username: smsdb
      password: zcl941217
      driver-class-name: oracle.jdbc.OracleDriver
  thymeleaf:
    mode: HTML5
    cache: false
  #字符集和json格式工具
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 10MB
  application:
    name: disapatch
    #reids 配置
  redis:
    host: 127.0.0.1
    port: 6379

#mybatis配置
mybatis:
  type-aliases-package: com.wlwx.dispatch.entity
  #mapper加载路径
  mapper-locations: classpath:mapper/*.xml
  #myatbis配置文件
  config-location: classpath:mybatis-conf.xml

cust:
  smstask:
    logname: D:\\logs\\cust\\smslog.log


dispatch:
  datCoreSize : 16
  datMaxSize : 16
  datQueueSize : 100000
  maxSendRate : 5000
  custId : 4995
  firstSmsCustId : 4995
  custCode : 1000
  custPassword : 10000
  firstCustCode : 10000
  firstCustPassword : 10000
  reportSleepTime : 10000
  moSleepTime : 10000
  reportMoPort : 9001
  baseUrl : 172.20.0.56:8866
  sendRate : 2222

logging:
  config: classpath:log4j2.xml

